name: mailandcalendaruppa
description: Une application pour consulter facilement les mails et l'emploi dut temps de l'université. On peut aussi y ajouter des notes personnalisées.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

#environment:
#  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.12.2
  shared_preferences: ^0.5.10
  path_provider: 1.6.14
  url_launcher: ^5.7.5
  flutter_markdown: 0.4.4
  uuid: 2.2.2
  html: 0.14.0+3
  firebase_analytics: 6.0.0
  firebase_crashlytics: 0.1.4+1
  package_info: 0.4.3
  after_layout: 1.0.7+2
  flutter_calendar:
    git: git://github.com/Pyozer/flutter_calendar
  device_calendar: 3.1.0

  flutter_material_color_picker: 1.0.5
  introduction_screen: 1.0.9
  flutter_rounded_date_picker:
    git: git://github.com/Pyozer/flutter_rounded_date_picker

  outline_material_icons: 0.1.1
  timezone: 0.5.7
  flutter_native_timezone: 1.0.4
  qrcode_reader: 0.4.4

  cupertino_icons: ^0.1.3
  responsive_scaffold: ^0.0.2
  floating_search_bar: ^0.3.0

  enough_mail: ^0.0.33
  #intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.5

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/raw/
   - assets/i18n/
   - packages/timezone/data/2020a_all.tzf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          style: normal
          weight: 500

        - asset: assets/fonts/GoogleSans-Medium.ttf
          style: normal
          weight: 600

        - asset: assets/fonts/GoogleSans-Bold.ttf
          style: normal
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon_circle.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"